name: Build Multi-Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install Rust targets for macOS
        if: matrix.platform == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Build the app (macOS Universal)
        if: matrix.platform == 'macos-latest'
        run: npm run tauri build -- --target universal-apple-darwin

      - name: Build the app (Windows)
        if: matrix.platform == 'windows-latest'
        run: npm run tauri build

      - name: Build the app (Linux)
        if: matrix.platform == 'ubuntu-20.04'
        run: npm run tauri build

      - name: Upload artifacts (macOS Universal - DMG)
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal-dmg
          path: src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
          if-no-files-found: warn

      - name: Upload artifacts (macOS Universal - App Bundle)
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal-app
          path: src-tauri/target/universal-apple-darwin/release/bundle/macos/*.app
          if-no-files-found: warn

      - name: Upload artifacts (Windows EXE)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: src-tauri/target/release/music-visualizer.exe

      - name: Upload artifacts (Windows MSI Installer)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi-installer
          path: src-tauri/target/release/bundle/msi/*.msi

      - name: Upload artifacts (Linux)
        if: matrix.platform == 'ubuntu-20.04'
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: src-tauri/target/release/bundle/appimage/*.AppImage

